services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - hf_cache:/root/.cache/huggingface
      - qdrant_storage:/qdrant/storage
    restart: always

  backend:
    build: .
    container_name: meme_search_api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    volumes:
      - ./data/images:/workspace/data/images
    depends_on:
      - qdrant
    restart: always

volumes:
  qdrant_storage: